[project]
name = "gemma3-pdf-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ollama>=0.4.7",
    "pydantic>=2.11.0",
    "pymupdf>=1.25.4",
    "streamlit>=1.44.0",
]
